platform :ios, '8.0'
use_frameworks!

pod 'CocoaLumberjack', '2.0.0'
pod 'ReactiveCocoa'
pod 'AFNetworking'
pod 'Reachability'
pod 'Masonry'
pod 'CLAFluxDispatcher'
pod 'SocketRocket'
pod 'ObjectiveSugar'
pod 'UIImage+ImageWithColor'
pod 'CSStickyHeaderFlowLayout', '0.2.6'
pod 'UIImageEffects'
pod 'DZNEmptyDataSet'
pod 'JSQMessagesViewController'
pod 'SDWebImage'
pod 'Mantle'
pod 'M13BadgeView'
pod 'NJKWebViewProgress'
pod 'SVProgressHUD'
pod 'NSDate-Extensions'
pod 'JDStatusBarNotification'
pod 'RMPhoneFormat', :git => 'https://github.com/rromanchuk/RMPhoneFormat'
